<#
.SYNOPSIS
Get-LOG-MD_z_Cleanup_All.ps1 is designed to remove all items and reports 
that were generated by LOG-MD for the variable:
 * $ARTHIR_Dir

MITRE ATT&CK Technique IDs:  none

Make sure that this is the LAST module in the modules.conf so it runs last
after all results are copied back to the host system launching ARTHIR. 

If you want to remove the binary from remote systems after it has run use the cleanup module
of the $DeleteAll variable to remove all files.

Adjust the variables to what you want to do with each item:
  $ARTHIR_Dir					Set to a directory you want the results of the modules to be stored for harvesting
  $ARTHIR_OutputDir 			Set to a directory you want the results of the modules to be stored for harvesting
  $RenameReports 				Yes/No - Rename the reports to include the systemname or what you specify with $SysName variable
  $SysName						What you want each report to be pre-pended with such as "computername"
  $WriteEventLogEntry			Create an event log entry that this module ran 'Yes' or 'No'
  $EventSource					The name of the source the event will be written to the Application log (default is ARTHIR)
  $Event_ID						What event ID to use in the log entry
  $DeleteAll					Yes/No - Deletes all the reports, tool and directory after the module has completed
  
.NOTES
This is a script, no download or binary needed
#>
$Tool_Name = "LOG-MD.exe"
$ARTHIR_Dir = "C:\Program Files\LMD"
$SysName = $env:computername
$WriteEventLogEntry = "Yes"
$EventSource = "ARTHIR"
$Event_ID = "1337"
$DeleteAll = "Yes"
#
#  Cleanup/Delete if specified
#
If ($DeleteAll -eq 'No') {
  Write-Output "Tool and reports not being deleted"
  }  
  else {
    Get-Process $Tool_Name -ErrorAction SilentlyContinue | Stop-Process -PassThru
    cd..
    Remove-Item -path $ARTHIR_Dir -recurse -force
}
#
#  Write log entry
#
If ($WriteEventLogEntry -eq 'No') {
  Break
  }  
  elseif ([System.Diagnostics.EventLog]::SourceExists($EventSource) -eq $False) {
    New-EventLog -LogName Application -Source $EventSource
    Write-EventLog -LogName Application -EntryType Information -EventId $Event_ID -Source $EventSource -Message 'LOG-MD Cleanup completed deleting all files and reports executed by Arthir'
 }
  else {
    Write-EventLog -LogName Application -EntryType Information -EventId $Event_ID -Source $EventSource -Message 'LOG-MD Cleanup completed deleting all files and reports executed by Arthir'
    }
